permissions:
  contents: read

env:
  RPC_URL: ${{ secrets.RPC_URL }}
  RUST_LOG: "info,fireblocks_solana_signer=debug"
  FIREBLOCKS_ENDPOINT: ${{ vars.FIREBLOCKS_ENDPOINT }}
  FIREBLOCKS_POLL_TIMEOUT: "30"
  FIREBLOCKS_POLL_INTERVAL: "3"
  FIREBLOCKS_DEVNET: "true"
  FIREBLOCKS_VAULT: "0"
on:
  workflow_dispatch:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: build
jobs:
  build:
    runs-on: ${{ vars.RUNNER }}
    name: build cli
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ubicloud/rust-cache@v2
        with:
          cache-on-failure: "true"
          cache-all-crates: "true"
          workspaces: |
            . -> target
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
      - name: install deps
        run: |
          sudo apt-get install -y libgpgme-dev libhidapi-dev libudev-dev
      - uses: CarteraMesh/fireblocks-config-action@v1
        id: config
        with:
          fireblocks-secret: |
            ${{ secrets.FIREBLOCKS_SECRET }}
          fireblocks-api-key: ${{ secrets.FIREBLOCKS_API_KEY }}
          fireblocks-endpoint: ${{ vars.FIREBLOCKS_ENDPOINT }}
          solana-rpc-url: ${{ secrets.RPC_URL }}
      - name: test clap-utils
        run: |
          cargo test -p solana-clap-utils --lib --tests -- --nocapture
      - name: test clap-v3-utils
        run: |
          cargo test -p solana-clap-v3-utils --lib --tests -- --nocapture
      - name: build
        run: |
          cargo build
      - name: test
        run: |
          echo "using ${steps.config.outputs.solana-config-path}"
          ./scripts/test.sh "${{ steps.config.outputs.solana-config-path }}"
