name: Release Solana CLI

on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ${{ vars.RUNNER }}
            target: x86_64-unknown-linux-gnu
            name: linux-amd64
            deps: "libudev-dev"
          - os: macos-latest
            target: aarch64-apple-darwin
            name: macos-arm64
            deps: ""

    runs-on: ${{ matrix.os }}
    name: Build ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0 # Need full history for git describe
      - name: Check tag
        id: tag
        run: |
          if [[ ! $GITHUB_REF == refs/tags/* ]]; then
            echo "This action can only be run on tag events!"
            exit 1
          fi
          echo _tag=${GITHUB_REF#refs/tags/} >> $GITHUB_OUTPUT

      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main

      - name: Install dependencies
        if: matrix.deps != ''
        run: ${{ matrix.deps }}

      - name: Build cli release binary
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Create release archive
        shell: bash
        run: |
          mkdir -p release
          for i in fb-solana fb-spl-token; do
            cp target/${{ matrix.target }}/release/$i release/
            tar -C release -czf ${i}-${{ steps.tag.outputs._tag }}-${{ matrix.name }}.tar.gz $i
          done
          ls -la release

      - name: Upload artifact solana-cli
        uses: actions/upload-artifact@v4
        with:
          name: fb-solana-${{ matrix.name }}
          path: release/fb-solana-${{ steps.tag.outputs._tag }}-${{ matrix.name }}.*
      - name: Upload artifact spl-token
        uses: actions/upload-artifact@v4
        with:
          name: fb-spl-token-${{ matrix.name }}
          path: release/fb-spl-token-${{ steps.tag.outputs._tag }}-${{ matrix.name }}.*
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs._tag }}
          files: |
            fb-solana-${{ steps.tag.outputs._tag }}-${{ matrix.name }}.tar.gz
            fb-spl-token-${{ steps.tag.outputs._tag }}-${{ matrix.name }}.tar.gz
