permissions:
  contents: read

env:
  RUST_LOG: "info,fireblocks_solana_signer=debug"
on:
  workflow_dispatch:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: test
jobs:
  build:
    runs-on: ${{ vars.RUNNER }}
    name: build clis
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
        with:
          ubuntu_packages: "libhidapi-dev libudev-dev libgpgme-dev"
      - uses: CarteraMesh/fireblocks-config-action@main
        id: config
        with:
          fireblocks-secret: |
            ${{ secrets.FIREBLOCKS_SECRET }}
          fireblocks-api-key: ${{ secrets.FIREBLOCKS_API_KEY }}
          fireblocks-endpoint: ${{ vars.FIREBLOCKS_ENDPOINT }}
          solana-rpc-url: ${{ secrets.RPC_URL }}
          commitment: finalized
      - name: test clap-utils
        run: |
          cargo test -p solana-clap-utils --lib --tests -- --nocapture
      - name: test clap-v3-utils
        run: |
          cargo test -p solana-clap-v3-utils --lib --tests -- --nocapture
      - name: test cli-config
        run: |
          cargo test -p solana-cli-config --lib --tests -- --nocapture
      - name: cargo build
        run: |
          cargo build
      - name: test
        run: |
          echo "using ${{ steps.config.outputs.solana-config-path }}"
          cat "${{ steps.config.outputs.solana-config-path }}"
          echo
          ./cli-tests/test.sh "${{ steps.config.outputs.solana-config-path }}"
